model_args:
  mode: train
  model_type: DDIM  # Updated to match input
  resume_epoch: null

data_args:
  img_size: 128
  num_img_channels: 1
  dataset: fastMRI_NYU
  label_csv_dir: "/home/lc2382/project/segmentation-guided-diffusion/data/labels/t2_slice_level_labels_reversed.csv"
  img_dir: "/home/lc2382/project/fastMRI_NYU/nifti"
  seg_dir: "/home/lc2382/project/segmentation-guided-diffusion/data/CG+PZ_seg"
  segmentation_guided: true
  neighboring_images_guided: true
  segmentation_channel_mode: single
  num_segmentation_classes: 3

training_args:
  train_batch_size: 32  # Updated to match input
  eval_batch_size: 32  # Updated to match input
  num_epochs: 400
  gradient_accumulation_steps: 1
  learning_rate: 0.00001
  lr_warmup_steps: 500
  save_image_epochs: 40
  save_model_epochs: 40
  mixed_precision: fp16  # Default remains as 'fp16'
  class_conditional: true
  cfg_training: true
  num_class_embeds: 5
  output_dir: null
  save_forward_process: true
  use_squaredcos_cap_v2_scheduler: true

  use_ablated_segmentations: false
  eval_noshuffle_dataloader: false
  seed: 10383
  

test_args:
  cfg_eval: true
  fake_labels: true
  eval_batch_size: 16
  eval_mask_removal: false
  eval_blank_mask: false
  eval_sample_size: 1000

experimental_args:
  cfg_p_uncond: 0.2
  cfg_weight: 2.0
  trans_noise_level: 0.5
  use_cfg_for_eval_conditioning: true
  cfg_maskguidance_condmodel_only: true

additional_args:
  push_to_hub: false
  hub_private_repo: false
  overwrite_output_dir: true
  debug_save_image: true
